In [1]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)



from RLDecon.get_inputs import get_inputs
from RLDecon.run_decon import run_5d_decon

variables = get_inputs()
if variables is not None:
    [input_file_str, dat, mdata, psfs, z_spacing, niter, pad_amount, channel] = variables
    
    # run_5d_decon(input_file_str, dat, mdata, psfs, z_spacing[0], niter[0], pad_amount, channel)





Num GPUs Available:  1
2
1
No metadata found, generating metadata, please check


In [11]:
mdata

NameError: name 'mdata' is not defined

In [6]:
import tifffile

input_file_str = 'TestData/slide2_deskewed_capture1_cropped_488.ome.tif' 
with tifffile.TiffFile(input_file_str) as tif:
    # print(dir(tif))
    # if 'ome.tif' in input_file_str:
    #     xml_data = tif.ome_metadata
    #     mdata = 
    # else
    #     mdata = tif.imagej_metadata
    
    
    dat = tif.asarray()





In [7]:
dat.shape

(2, 59, 210, 201)

In [9]:
from skimage import io
io.imsave('TestData/slide2_nometadata.tif', dat)

C:\Users\u1604360\AppData\Local\Temp\ipykernel_18020\2305662545.py:2: UserWarning: TestData/slide2_nometadata.tif is a low contrast image
  io.imsave('TestData/slide2_nometadata.tif', dat)


In [14]:
16756/59

284.0

In [5]:
ls TestData/slide2_deskewed_capture1_cropped_488.ome.tif

Parameter format not correct - "slide2_deskewed_capture1_cropped_488.ome.tif".


In [11]:
imagej_mdata

In [4]:
ls Z:\Shared243\storal\2024-01-30_mc191\slide2_deskewed_capture1_cropped_488.ome.tif

 Volume in drive Z is SYSTEM
 Volume Serial Number is ECF6-6273

 Directory of Z:\Shared243\storal\2024-01-30_mc191

01/03/2024  13:02    <DIR>          .
07/03/2024  12:37    <DIR>          ..
07/02/2024  11:03         3,484,551 488PSF.ome.tif
07/02/2024  16:45                81 488PSF_sigma.csv
07/02/2024  11:03         3,484,697 640PSF.ome.tif
07/02/2024  16:46                78 640PSF_sigma.csv
30/01/2024  11:59        21,713,960 PSFs.sld
30/01/2024  15:41    69,358,899,970 slide1.sld
30/01/2024  16:36    17,970,957,416 slide2.sld
07/02/2024  11:15    26,004,795,186 slide2_deskewed.sld
07/02/2024  14:23     1,451,100,591 slide2_deskewed_capture1_cropped_488.ome.tif
01/03/2024  12:35     5,663,503,340 slide2_deskewed_capture1_cropped_488_flowdec_deconvolved_rl10_averagedpsf.ome.tif
01/03/2024  12:13     5,663,503,340 slide2_deskewed_capture1_cropped_488_flowdec_deconvolved_rl10_onthedaypsf.ome.tif
07/02/2024  14:22     1,451,100,591 slide2_deskewed_capture1_cropped_640.ome.tif
08/02

In [1]:
a =[]
a.append(1)

In [15]:
import tifffile.tifffile
input_file_str= 'E:/David/Deconvolution-tests/tiffs/Scott/slide1_capture1_2024-01-26_deskew_C0.tif'
with tifffile.TiffFile(input_file_str) as tif:
        mdata = tif.imagej_metadata
        dat = tif.asarray()

In [16]:
mdata

{'ImageJ': '1.54f',
 'images': 59,
 'slices': 59,
 'unit': '\\u00B5m',
 'spacing': 0.271,
 'loop': False,
 'min': 0.0,
 'max': 132.0,
 'Info': 'Software: SlideBook\nDateTime: 2024:02:17 08:52:45\n'}

In [4]:
b =(1,2,3,4)

In [8]:
import numpy as np
np.expand_dims(b, 1)

array([[1],
       [2],
       [3],
       [4]])

In [ ]:

E:\anaconda3\envs\FlowDec\python.exe C:\Users\u1604360\AppData\Roaming\Python\Python38\Scripts\pyinstaller.exe --onefile --add-binary="E:\anaconda3\envs\FlowDec\Library\bin\cudart64_110.dll;." --add-binary="E:\anaconda3\envs\FlowDec\Library\bin\cublas64_11.dll;." RLDecon.py 

In [ ]:
python.exe --onefile RLDecon.py 

In [5]:
psf640

array([[4.1770e+00, 1.0873e-03, 9.4708e-04],
       [1.0873e-03, 3.7246e+00, 8.1359e-01],
       [9.4708e-04, 8.1359e-01, 2.1981e+01]])

In [4]:
# bead488_image_file_str = "Z:/Shared243/storal/2024-01-30_mc191/488PSF_sigma.csv"
bead488_image_file_str = choose_image_file(default_folder = 'Z:/Shared243/storal/', title_message = 'Select the 488 PSF', csv = True)
psf488 = np.genfromtxt(bead488_image_file_str, delimiter=',')

# bead640_image_file_str = "Z:/Shared243/storal/2024-01-30_mc191/640PSF_sigma.csv"
bead640_image_file_str = choose_image_file(default_folder = 'Z:/Shared243/storal/', title_message = 'Select the 640 PSF', csv = True)
psf640 = np.genfromtxt(bead640_image_file_str, delimiter=',')





In [8]:


class NumericInputDialog(simpledialog.Dialog):
    def __init__(self, master, dialog_title="Input", prompt="Enter a number:", default_value=0, validator=float, **kwargs):
        
        self.prompt = prompt
        self.default_value = default_value
        self.validator = validator  # Use 'float' for floats, 'int' for integers
        self.dialog_title = dialog_title 
        super().__init__(master, **kwargs)

    def body(self, master):
        self.title(self.dialog_title)
        tk.Label(master, text=self.prompt).grid(row=0)

        self.value_entry = tk.Entry(master)
        self.value_entry.grid(row=0, column=1)
        self.value_entry.insert(0, str(self.default_value))
        
        return self.value_entry

    def apply(self):
        value_str = self.value_entry.get()
        try:
            self.result = self.validator(value_str)
        except ValueError:
            messagebox.showwarning("Invalid input", f"Please enter a valid {self.validator.__name__}.")
            self.result = None

def get_numeric_input( title, prompt, default_value, validator):
    # Example usage:
    root = tk.Tk()
    root.withdraw()  # Hide the root window
    dialog = NumericInputDialog(root, dialog_title = title, prompt=prompt, default_value=default_value, validator=validator)
    root.destroy()
    return dialog.result





# For float input
z_spacing = get_numeric_input( "Confirm Z spacing", "Input Z spacing of Image:", mdata['spacing']*10, float)


while(z_spacing is None):
    print("No valid float was entered.")
    z_spacing = get_numeric_input( "Confirm Z spacing", "Input Z spacing of Image:", mdata['spacing']*10, float)

print("User entered z_spacing:", z_spacing)
# 


# For integer input



niter = get_numeric_input( "Input Integer", "Enter number of RL iterations:", 10, int)
while(niter is None):
    print("No valid int was entered.")
    niter = get_numeric_input( "Input Integer", "Enter number of RL iterations:", 10, int)

print("RL iterations:", niter)



pad_amount = get_numeric_input( "Input Integer", "Enter padding amount:", 16, int)
while(pad_amount is None):
    print("No valid int was entered.")
    niter = get_numeric_input( "Input Integer", "Enter padding amount:", 16, int)

print("Padding amount:", pad_amount)


User entered z_spacing: 2.705078125
RL iterations: 10


No valid inputs were entered.


Deconvolving:   0%|          | 0/284 [00:00<?, ?it/s]

{'ImageJ': '1.54f',
 'images': 33512,
 'channels': 2,
 'slices': 59,
 'frames': 284,
 'hyperstack': True,
 'mode': 'grayscale',
 'unit': 'micron',
 'spacing': 0.2705078125,
 'loop': False,
 'min': 93.0,
 'max': 123.0,
 'Info': ' BitsPerPixel = 16\n DimensionOrder = XYCZT\n IsInterleaved = true\n IsRGB = false\n LittleEndian = true\n PixelType = uint16\n Series 0 Name = Capture 1 DR\n SizeC = 2\n SizeT = 285\n SizeX = 754\n SizeY = 512\n SizeZ = 59\nLocation = Z:\\Shared243\\storal\\2024-01-30_mc191\\slide2_deskewed.sld\n',
 'Labels': ['c:1/2 z:1/59 t:1/285 - Capture 1 DR',
  'c:2/2 z:1/59 t:1/285 - Capture 1 DR',
  'c:1/2 z:2/59 t:1/285 - Capture 1 DR',
  'c:2/2 z:2/59 t:1/285 - Capture 1 DR',
  'c:1/2 z:3/59 t:1/285 - Capture 1 DR',
  'c:2/2 z:3/59 t:1/285 - Capture 1 DR',
  'c:1/2 z:4/59 t:1/285 - Capture 1 DR',
  'c:2/2 z:4/59 t:1/285 - Capture 1 DR',
  'c:1/2 z:5/59 t:1/285 - Capture 1 DR',
  'c:2/2 z:5/59 t:1/285 - Capture 1 DR',
  'c:1/2 z:6/59 t:1/285 - Capture 1 DR',
  'c:2/2 z

In [31]:


kernel488 = get_kernel(psf488, z_spacing)
kernel640 = get_kernel(psf640, z_spacing)
data = np.copy(dat) 
res = np.zeros(data.shape)
ndim = 3 #data.ndim 
algo = fd_restoration.RichardsonLucyDeconvolver(ndim, pad_mode='none', pad_min=[32,32,32]).initialize() 

for i,image in tqdm(enumerate(data), total=data.shape[0], desc='Deconvolving: '):
    tt488 = image[:,0]
    nonzero = tt488[np.where(tt488>0)]
    bkgd_mode = stats.mode(nonzero)[0][0]
    bkgd_std = stats.tstd(nonzero)
    indz,indy,indx = np.where(tt488==0)
    tt488[indz, indy, indx] = bkgd_mode + bkgd_std*np.random.randn(len(indz))
    # Note that deconvolution initialization is best kept separate from 
    # execution since the "initialize" operation corresponds to creating 
    # a TensorFlow graph, which is a relatively expensive operation and 
    # should not be repeated across iterations if deconvolving more than 
    # one image
    res[i, :, 0] = algo.run(fd_data.Acquisition(data=tt488, kernel=kernel488), niter=niter).data

    tt640 = image[:,1]
    nonzero = tt640[np.where(tt640>0)]
    bkgd_mode = stats.mode(nonzero)[0][0]
    bkgd_std = stats.tstd(nonzero)
    indz,indy,indx = np.where(tt640==0)
    tt640[indz, indy, indx] = bkgd_mode + bkgd_std*np.random.randn(len(indz))
    # Note that deconvolution initialization is best kept separate from 
    # execution since the "initialize" operation corresponds to creating 
    # a TensorFlow graph, which is a relatively expensive operation and 
    # should not be repeated across iterations if deconvolving more than 
    # one image
    res[i, :, 1] = algo.run(fd_data.Acquisition(data=tt640, kernel=kernel640), niter=niter).data

suffix = f"_scottdecon_niter{niter}_padding32.tif"
output_file_str = input_file_str.replace(".tif", suffix)
####################
# print('Done. Now writing to file\n')
# # create numpy array with correct order
# if is_single_time_pt:
#     img5d = np.expand_dims(np.expand_dims(res, axis=1), axis=0) 
# else:
#     img5d = np.expand_dims(res, axis=1)
# # write file and save OME-XML as description
tifffile.imwrite(output_file_str, res.astype(np.uint16), imagej = True, metadata=mdata)
print('All finished\n')

'_scottdecon_niter5_padding32.tif'

In [33]:
output_file_str

'Z:/Shared243/storal/2024-01-30_mc191/test_scott/slide2_deskewed_cropped_scottdecon_niter5_padding32.tif'

All finished



In [8]:
dat

array([[[[[112, 102, 102, ..., 103, 105, 105],
          [102, 102, 103, ..., 100, 101,  99],
          [102, 101, 103, ..., 103, 104, 107],
          ...,
          [102, 102, 100, ..., 104, 102, 104],
          [101, 103, 101, ..., 100, 101, 101],
          [103, 103, 104, ..., 102, 103, 102]],

         [[ 98, 101, 102, ..., 100, 100,  99],
          [101, 101, 103, ..., 101, 101, 100],
          [102, 104, 104, ..., 101, 100, 103],
          ...,
          [104, 102, 103, ..., 104, 103, 104],
          [ 98, 106, 103, ..., 100,  96, 104],
          [106, 103,  97, ..., 104, 105,  99]]],


        [[[101, 104, 101, ..., 102, 104, 107],
          [104, 104, 106, ..., 104, 100,  99],
          [102, 104, 101, ..., 102,  99, 101],
          ...,
          [102, 104, 101, ..., 103, 100, 102],
          [100,  98, 104, ..., 102, 101, 104],
          [103, 106, 102, ..., 101, 104, 104]],

         [[100, 101, 105, ...,  97, 104, 102],
          [103, 102, 107, ..., 103, 103, 105],
       

In [ ]:


dat = tifffile.imread(input_file_str)
psf = np.genfromtxt(bead_image_file_str, delimiter=',')
print("Data successfully read in \n")

kernel = np.zeros(kernel_shape) #(51,51,51)) #Note may not work if this size is too big relative to the image
for offset in [0,1]:
    kernel[tuple((np.array(kernel.shape) - offset) // 2)] = 1
#assume bead image at different resolution in z to actual data, and difference is a factor of 3.08 (308nm versus 100nm)
#estimated and stored 3d psf, but assume here diagonal psf. Could adjust this, but already very close to diagonal
kernel = ndimage.gaussian_filter(kernel, sigma=[np.sqrt(psf[2,2])/2.705078,np.sqrt(psf[0,0]),np.sqrt(psf[1,1])])

############

data = np.copy(dat) 
res = np.zeros(data.shape)
ndim = 3 #data.ndim 
algo = fd_restoration.RichardsonLucyDeconvolver(ndim, pad_mode='none', pad_min=[16,16,16]).initialize() 
tmp = algo.run(fd_data.Acquisition(data=data[0], kernel=kernel), niter=2)
for tt in range(SizeT):
    if tt%10==0:
        print(str(tt)+' of ' + str(SizeT) + ' complete')
    nonzero = data[tt][np.where(data[tt]>0)]
    bkgd_mode = stats.mode(nonzero)[0][0]
    bkgd_std = stats.tstd(nonzero)
    indz,indy,indx = np.where(data[tt]==0)
    data[tt,indz, indy, indx] = bkgd_mode + bkgd_std*np.random.randn(len(indz))
    # Note that deconvolution initialization is best kept separate from 
    # execution since the "initialize" operation corresponds to creating 
    # a TensorFlow graph, which is a relatively expensive operation and 
    # should not be repeated across iterations if deconvolving more than 
    # one image
    res[tt] = algo.run(fd_data.Acquisition(data=data[tt], kernel=kernel), niter=niter).data

####################
print('Done. Now writing to file\n')
# create numpy array with correct order
if is_single_time_pt:
    img5d = np.expand_dims(np.expand_dims(res, axis=1), axis=0) 
else:
    img5d = np.expand_dims(res, axis=1)
# write file and save OME-XML as description
tifffile.imwrite(output_file_str, img5d, metadata={'axes': dimorder}, description=xml)
print('All finished\n')